<div class="separator trn_task"></div>
{if $tutorial == 4 || $queryString == "page=buildings" && $tutorial == 2}
<a title="Tutorial" class="big_btn green trn_task btn_menu btn_menu_big" style="width: 77%;padding-right: 0px;" href="#" onclick="qtip_modal('{$LNG.tutorial_require_solar}', '{$LNG.tutorial_lack_solar}<br /> <br /> <br /> <ul class=\'trn_ul\'>	<li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/4.gif\' alt=\'{$LNG.tech.4}\'>{$LNG.tutorial_up_solar}</li></ul>', '{$LNG.tutorial_close_info}', 450);">{$LNG.option_educ}</a>
<a title="{$LNG.tutorial_stop}" class="big_btn red trn_task btn_menu btn_menu_big" style="width: 13%;padding: 0px;margin-left: 1px;" href="game.php?page=training&mode=off">X</a>
   
{elseif $tutorial == 5 || $tutorial == 6 || $tutorial == 7 || $tutorial == 8}
<a title="Tutorial" class="big_btn green trn_task btn_menu btn_menu_big" style="width: 77%;padding-right: 0px;" href="#" onclick="qtip_modal('{$LNG.tutorial_metal}', '<p>{$LNG.tutorial_metal_1}</p><p>{$LNG.tutorial_metal_2_1}</p> <br /><br /> <ul class=\'trn_ul\'>	<li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/1.gif\' alt=\'{$LNG.tech.1}\'>{$LNG.tutorial_metal_3}: «{$LNG.tech.1}» {$LNG.tutorial_metal_4}.</li>	<li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/2.gif\' alt=\'{$LNG.tech.2}\'>{$LNG.tutorial_metal_3}: «{$LNG.tech.2}» {$LNG.tutorial_metal_5}.</li>	<li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/3.gif\' alt=\'{$LNG.tech.3}\'>{$LNG.tutorial_metal_3}: «{$LNG.tech.3}» {$LNG.tutorial_metal_6}.</li></ul>', '{$LNG.tutorial_close_info}', 550);">{$LNG.option_educ}</a>
<a title="Tutorial" class="big_btn red trn_task btn_menu btn_menu_big" style="width: 13%;padding: 0px;margin-left: 1px;" href="game.php?page=training&mode=off">X</a>
{elseif $tutorial == 9 || $tutorial == 10} 
<a title="Tutorial" class="big_btn green trn_task btn_menu btn_menu_big" style="width: 77%;padding-right: 0px;" href="#" onclick="qtip_modal('{$LNG.tutorial_metal_12}', '<p>{$LNG.tutorial_metal_13_1}</p> <br /><br /><ul class=\'trn_ul\'>	<li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/4.gif\' alt=\'{$LNG.tech.4}\'>{$LNG.tutorial_metal_3}: «{$LNG.tech.4}» {$LNG.tutorial_metal_14}.</li></ul>', '{$LNG.tutorial_close_info}', 550);">{$LNG.option_educ}</a>
<a title="Tutorial" class="big_btn red trn_task btn_menu btn_menu_big" style="width: 13%;padding: 0px;margin-left: 1px;" href="game.php?page=training&mode=off">X</a>
{elseif $tutorial == 14 && $queryString == "page=research" || $tutorial == 15 || $tutorial == 16 || $tutorial == 17 || $tutorial == 18 || $tutorial == 19}
<a title="{$LNG.option_educ}" class="big_btn green trn_task btn_menu btn_menu_big" style="width: 77%;padding-right: 0px;" href="#" onclick="qtip_modal('{$LNG.tutorial_metal_59}', '<p>{$LNG.tutorial_metal_45_1}</p><br /><br /> <ul class=\'trn_ul\'>	<li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/31.gif\' alt=\'{$LNG.tech.31}\'>{$LNG.tutorial_metal_3}: «{$LNG.tech.31}» {$LNG.tutorial_metal_48}.</li>	<li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/106.gif\' alt=\'{$LNG.tech.106}\'>{$LNG.tutorial_metal_17}: «{$LNG.tech.106}» {$LNG.tutorial_metal_5}.</li></ul>', '{$LNG.tutorial_close_info}', 550);">{$LNG.option_educ}</a>
<a title="Tutorial" class="big_btn red trn_task btn_menu btn_menu_big" style="width: 13%;padding: 0px;margin-left: 1px;" href="game.php?page=training&mode=off">X</a>
{elseif $tutorial == 21 && $queryString == "page=defense" || $tutorial == 21 || $tutorial == 22 || $tutorial == 23 || $tutorial == 24 || $tutorial == 25 || $tutorial == 26 || $tutorial == 27}
<a title="{$LNG.option_educ}" class="big_btn green trn_task btn_menu btn_menu_big" style="width: 77%;padding-right: 0px;" href="#" onclick="qtip_modal('{$LNG.option_train_5}', '<p>{$LNG.tutorial_metal_52}</p><p>{$LNG.tutorial_metal_53}</p><br /><br /> <ul class=\'trn_ul\'>	<li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/14.gif\' alt=\'{$LNG.tech.14}\'>{$LNG.tutorial_metal_3}: «{$LNG.tech.114}» {$LNG.tutorial_metal_5}.</li>	<li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/15.gif\' alt=\'{$LNG.tech.15}\'>{$LNG.tutorial_metal_3}: «{$LNG.tech.15}» {$LNG.tutorial_metal_5}.</li>	<li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/113.gif\' alt=\'{$LNG.tech.113}\'>{$LNG.tutorial_metal_17}: «{$LNG.tech.113}» {$LNG.tutorial_metal_5}.</li>	<li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/120.gif\' alt=\'{$LNG.tech.120}\'>{$LNG.tutorial_metal_17}: «{$LNG.tech.120}» {$LNG.tutorial_metal_4}.</li>	<li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/401.gif\' alt=\'{$LNG.tech.401}\'>{$LNG.tutorial_build}: «{$LNG.tech.401}» {$LNG.tutorial_metal_54}.</li>	<li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/402.gif\' alt=\'{$LNG.tech.402}\'>{$LNG.tutorial_build}: «{$LNG.tech.402}» {$LNG.tutorial_metal_55}.</li></ul>', '{$LNG.tutorial_close_info}', 550);">{$LNG.option_educ}</a>
<a title="Tutorial" class="big_btn red trn_task btn_menu btn_menu_big" style="width: 13%;padding: 0px;margin-left: 1px;" href="game.php?page=training&mode=off">X</a>
{elseif $tutorial == 32 || $tutorial == 33 || $tutorial == 34 || $tutorial == 35 || $tutorial == 36 || $tutorial == 37 || $tutorial == 38 || $tutorial == 39}
<a title="{$LNG.option_educ}" class="big_btn green trn_task btn_menu btn_menu_big" style="width: 77%;padding-right: 0px;" href="#" onclick="qtip_modal('{$LNG.tutorial_metal_42}', '<p>{$LNG.tutorial_metal_43}</p><p>{$LNG.tutorial_metal_44}</p><p>{$LNG.tutorial_metal_45}</p><br /><br /> <ul class=\'trn_ul\'>	<li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/15.gif\' alt=\'{$LNG.tech.15}\'>{$LNG.tutorial_metal_3}: «{$LNG.tech.15}» {$LNG.tutorial_metal_47}.</li>	<li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/113.gif\' alt=\'{$LNG.tech.113}\'>{$LNG.tutorial_metal_17}: «{$LNG.tech.113}» {$LNG.tutorial_metal_48}.</li>	<li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/110.gif\' alt=\'{$LNG.tech.110}\'>{$LNG.tutorial_metal_17}: «{$LNG.tech.110}» {$LNG.tutorial_metal_49}.</li>	<li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/115.gif\' alt=\'{$LNG.tech.115}\'>{$LNG.tutorial_metal_17}: «{$LNG.tech.115}» {$LNG.tutorial_metal_50}.</li>	<li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/209.gif\' alt=\'{$LNG.tech.209}\'>{$LNG.tutorial_build}: «{$LNG.tech.209}» {$LNG.tutorial_metal_51}.</li>	<li class=\'trn_li_demands\'>{$LNG.tutorial_metal_46}</li></ul>', '{$LNG.tutorial_close_info}', 550);">{$LNG.option_educ}</a>
<a title="Tutorial" class="big_btn red trn_task btn_menu btn_menu_big" style="width: 13%;padding: 0px;margin-left: 1px;" href="game.php?page=training&mode=off">X</a>
{elseif $tutorial == 42 || $tutorial == 43}
<a title="{$LNG.option_educ}" class="big_btn green trn_task btn_menu btn_menu_big" style="width: 77%;padding-right: 0px;" href="#" onclick="qtip_modal('{$LNG.tutorial_metal_90}', '<p>{$LNG.tutorial_metal_91}</p><br /><br /> <ul class=\'trn_ul\'>	<li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/601.jpg\' alt=\'{$LNG.tech.601}\'>{$LNG.tutorial_metal_69}: «{$LNG.tech.601}».</li>	<li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/602.jpg\' alt=\'{$LNG.tech.602}\'>{$LNG.tutorial_metal_69}: «{$LNG.tech.602}».</li></ul>', '{$LNG.tutorial_close_info}', 550);">{$LNG.option_educ}</a>
<a title="Tutorial" class="big_btn red trn_task btn_menu btn_menu_big" style="width: 13%;padding: 0px;margin-left: 1px;" href="game.php?page=training&mode=off">X</a>
{elseif $tutorial == 44 || $tutorial == 45}
<a title="{$LNG.option_educ}" class="big_btn green trn_task btn_menu btn_menu_big" style="width: 77%;padding-right: 0px;" href="#" onclick="qtip_modal('{$LNG.lm_academy}', '{$LNG.tutorial_metal_97}<br /><br /> <ul class=\'trn_ul\'>	<li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/1101.jpg\' alt=\'{$LNG.ally_fractions_9}\'>{$LNG.tutorial_metal_112}: «{$LNG.ally_fractions_9}».</li></ul>', '{$LNG.tutorial_close_info}', 550);">{$LNG.option_educ}</a>
<a title="Tutorial" class="big_btn red trn_task btn_menu btn_menu_big" style="width: 13%;padding: 0px;margin-left: 1px;" href="game.php?page=training&mode=off">X</a>
{elseif $tutorial == 51}
<a title="{$LNG.option_educ}" class="big_btn blue trn_task btn_menu btn_menu_big" style="width: 77%;padding-right: 0px;" href="#" onclick="qtip_modal('{$LNG.tutorial_metal_119}', '<p>{$LNG.tutorial_metal_120}.</p><p>{$LNG.tutorial_metal_121}</p><p>{$LNG.tutorial_metal_122}</p><p>{$LNG.tutorial_metal_123}</p><p>{$LNG.tutorial_metal_124}</p><br /><br /> <ul class=\'trn_ul\'>	<li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/208.gif\' alt=\'{$LNG.tech.208}\'>{$LNG.tutorial_build}: «{$LNG.tech.208}».</li>	<li class=\'trn_li_demands\'>{$LNG.tutorial_metal_125}</li></ul><br /><br /><p><span class=\'trn_span_reward\'>{$LNG.tutorial_metal_126}.</span></p>', '{$LNG.tutorial_close_info}', 550);">{$LNG.option_educ}</a>
<a title="Tutorial" class="big_btn red trn_task btn_menu btn_menu_big" style="width: 13%;padding: 0px;margin-left: 1px;" href="game.php?page=training&mode=off">X</a>
{elseif $tutorial == 54 || $tutorial == 55 || $tutorial == 56}
<a title="Обучение" class="big_btn blue trn_task btn_menu btn_menu_big" style="width: 77%;padding-right: 0px;" href="#" onclick="qtip_modal('{$LNG.tutorial_metal_131}', '<p>{$LNG.tutorial_metal_130}</p><br /><br /> <ul class=\'trn_ul\'>	<li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/124.gif\' alt=\'{$LNG.tech.124}\'>{$LNG.tutorial_metal_17}: «{$LNG.tech.124}» {$LNG.tutorial_metal_6}.</li><li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/203.gif\' alt=\'{$LNG.tech.203}\'>{$LNG.tutorial_build}: «{$LNG.tech.203}» 1.000 {$LNG.tutorial_metal_128}.</li><li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/204.gif\' alt=\'{$LNG.tech.204}\'>{$LNG.tutorial_build}: «{$LNG.tech.204}» 10.000 {$LNG.tutorial_metal_128}.</li><li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/207.gif\' alt=\'{$LNG.tech.207}\'>{$LNG.tutorial_build}: «{$LNG.tech.207}» 1.500 {$LNG.tutorial_metal_128}.</li><li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/209.gif\' alt=\'{$LNG.tech.209}\'>{$LNG.tutorial_build}: «{$LNG.tech.209}» 5 {$LNG.tutorial_metal_128}.</li>	<li class=\'trn_li_demands\'>{$LNG.tutorial_metal_129}</li></ul><br /><br /><p><span class=\'trn_span_bonus\'>{$LNG.donation_amountget}:</span></p><ul class=\'trn_ul\'>	<li class=\'trn_li_bonus\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/204.gif\' alt=\'{$LNG.tech.204}\'>«{$LNG.tech.204}» 150.000 {$LNG.tutorial_metal_128}.</li>	<li class=\'trn_li_bonus\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/205.gif\' alt=\'{$LNG.tech.205}\'>«{$LNG.tech.205}» 24.000 {$LNG.tutorial_metal_128}.</li>	<li class=\'trn_li_bonus\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/206.gif\' alt=\'{$LNG.tech.206}\'>«{$LNG.tech.206}» 49.000 {$LNG.tutorial_metal_128}.</li>	<li class=\'trn_li_bonus\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/207.gif\' alt=\'{$LNG.tech.207}\'>«{$LNG.tech.207}» 9.850 {$LNG.tutorial_metal_128}.</li>	<li class=\'trn_li_bonus\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/215.gif\' alt=\'{$LNG.tech.215}\'>«{$LNG.tech.215}» 3.500 {$LNG.tutorial_metal_128}.</li>	<li class=\'trn_li_bonus\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/219.gif\' alt=\'{$LNG.tech.219}\'>«{$LNG.tech.219}» 25 {$LNG.tutorial_metal_128}.</li></ul>', '{$LNG.tutorial_close_info}', 550);">{$LNG.option_educ}</a>
<a title="Tutorial" class="big_btn red trn_task btn_menu btn_menu_big" style="width: 13%;padding: 0px;margin-left: 1px;" href="game.php?page=training&mode=off">X</a>
{elseif $tutorial == 58}
<a title="Обучение" class="big_btn blue trn_task btn_menu btn_menu_big" style="width: 77%;padding-right: 0px;" href="#" onclick="qtip_modal('Первая экспедиция в сектор хостаил', '<p>Необходимо снарядить экспедицию в сектор хостаил</p><p>В секторе «Хостаил» есть четыре цели это Варвары, Пираты, Чужие и Руины. Полеты на первые три цели необходимо для поиска апгрейдов которые вам пригодятся для улучшение боевых характеристик флота и обороны. Так же там можно найти очки академии и темную материю, а в случаи если ваш состав флота подобран оптимально, то вы можете вывести и некоторое количество ресурсов оттуда. Однако для поиска ресурсов, особенно начинающим игрокам, лучше подойдет полеты в Руины, противник в них значительно слабее, а минимальное количество флота меньше. Важно помнить что для того что бы ресурсы были погружены на бор после боя в секторе “Хостаил” в составе вашего флота должны быть переработчики.</</p><br /><br /> <ul class=\'trn_ul\'>	<li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/205.gif\' alt=\'\'>Постройте: «Тяжёлый истребитель» 990 штук.</li><li class=\'trn_li_demands\'><img class=\'trn_ul_li_img\' src=\'./styles/theme/gow/gebaeude/206.gif\' alt=\'\'>Постройте: «Крейсер» 1.000 штук.</li>	<li class=\'trn_li_demands\'>Отправьте экспедицию в сектор хостаил</li></ul><br /><br /><p><span class=\'trn_span_reward\'>Вы получите 1.000 очков боевого опыта.</span></p>', '{$LNG.tutorial_close_info}', 550);">{$LNG.option_educ}</a>
<a title="Tutorial" class="big_btn red trn_task btn_menu btn_menu_big" style="width: 13%;padding: 0px;margin-left: 1px;" href="game.php?page=training&mode=off">X</a>
{/if}


